learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    path('users/', include('users.urls', namespace='users')),
)

learning_logs/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: yunongxin
# @Date: 2019-04-18

"""定义learning_logs的url模式"""

from django.urls import path
from . import views #导入视图

app_name = 'learning_logs' #必须包含该app的命名空间，否则会报错

urlpatterns = [
    # 主页
    path('', views.index, name = 'index'),
    path('topics/', views.topics, name = 'topics'),
    # 特定主页的详细页面
    path('topics/<int:topic_id>/', views.topic, name = 'topic'),
    # 用于添加新主题的网页
    path('new_topic/', views.new_topic, name = 'new_topic'),
    # 用于添加新条目的网页
    path('new_entry/<int:topic_id>/', views.new_entry, name = 'new_entry'),
    # 用于编辑条目的网页
    path('edit_entry/<int:entry_id>/', views.edit_entry, name = 'edit_entry')
]

users/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: yunongxin
# @Date: 2019-04-19

from django.urls import path
from django.contrib.auth.views import LoginView # Django2.0登录视图和1.X不一样了

from . import views

app_name = 'users'

urlpatterns = [
    # 登录页面
    path('login/', LoginView.as_view(template_name= 'users/login.html'), name = 'login'),
    # 注销页面
    path('logout/', views.logout_view, name = 'logout'),
    # 注册页面
    path('register/', views.register, name = 'register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的知识"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE) #on_delete在定义外键是避免两个表数据不一致
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50]+'...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: yunongxin
# @Date: 2019-04-19

from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''} #不生成标签

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})} # 定义一个HTML小部件，提供一个文本区域

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse # Django2.0中django.core.urlresolvers被迁移到了django.urls中
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry #从模型文件中导入Topic模型
from .forms import TopicForm, EntryForm


# Create your views here.

def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(owner = request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """显示单个主题和其所有的条目"""
    topic = Topic.objects.get(id = topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据，创建新表单
        form = TopicForm()
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """添加新条目"""
    topic = Topic.objects.get(id = topic_id)

    if request.method != 'POST':
        form = EntryForm
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username = new_user.username,
                                              password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  <body>
    <!-- static navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarToggleDemo02" aria-controls="navbarToggleDemo02"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarToggleDemo02" class="collapse navbar-collapse">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {%  if user.is_authenticated %}
              <span class="navbar-text">Hello, {{ user.username }}.</span>
              <li class="nav-item active"><a class="nav-link" href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li class="nav-item active"><a class="nav-link" href="{% url 'users:register' %}">Register</a></li>
              <li class="nav-item active"><a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="border-bottom mt-4">
        {% block header %}{% endblock header %}
      </div>
      <div class="mt-2">
        {% block content %}{% endblock content %}
      </div>
    </div><!-- /container -->
  </body>
</html>

templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>edit entry</title>
  </head>
  <body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap4 %}
    {% block header %}
      <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
    {% endblock %}
    {% block content %}
      <p>Edit entry:</p>
      <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary btn-sm">save changes</button>
        {% endbuttons %}
      </form>
    {% endblock content %}
  </body>
</html>

templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Learning Log</title>
  </head>
  <body>
    {% extends "learning_logs/base.html" %}

    {% block header %}
      <div class="jumbotron mt-2">
        <h1>Track your learning.</h1>
      </div>
    {% endblock header %}

    {% block content %}
      <h3>
        <a href="{% url 'users:register' %}">Register an Account</a> to make
        your own Learning Log, and list the topics you're learning about.
      </h3>
      <h3>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.
      </h3>
    {% endblock content%}
  </body>
</html>

templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>new entry</title>
  </head>
  <body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap4 %}
    {% block header %}
      <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
    {% endblock header %}

    {% block content %}
      <p>Add new entry:</p>
      <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary btn-sm">add entry</button>
        {% endbuttons %}
      </form>
    {% endblock content %}
  </body>
</html>

templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>new topic</title>
  </head>
  <body>
    {% extends "learning_logs/base.html" %}
    {% load bootstrap4 %}
    {% block header %}
      <h2>Add a new topic:</h2>
    {% endblock header %}
    {% block content %}

      <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary btn-sm">add topic</button>
        {% endbuttons %}
      </form>
    {% endblock content %}
    
  </body>
</html>

templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Title</title>
  </head>
  <body>
    {% extends 'learning_logs/base.html' %}

    {% block header %}
      <h2>{{ topic }}</h2>
    {% endblock header %}

    {% block content %}
      <div class="mt-2 mb-2">
        <a href="{% url 'learning_logs:new_entry' topic.id %}"><button type="button" class="btn btn-sm">add new entry</button></a>
      </div>
      {% for entry in entries %}
        <div class="card">
          <div class="card-header">
            <h3>
              {{ entry.date_added|date:'M d, Y H:i' }}
              <small>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}"><button type="button" class="btn btn-sm">edit entry</button></a>
              </small>
            </h3>
          </div>
          <div class="card-body">
            {{ entry.text|linebreaks }}
          </div>
        </div><!-- bootstrap4 使用card -->
        <br />
      {% empty %}
        There are no entries for this topic yet.
      {% endfor %}
    {% endblock content %}
  </body>
</html>

templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Title</title>
  </head>
  <body>
    {% extends "learning_logs/base.html" %}

    {% block header %}
      <h1>Topics</h1>
    {% endblock header %}

    {% block content %}

      <ul class="list-group">
      {% for topic in topics%}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          </h3>
        </li>
      {% empty %}
        <li>No topics have been added</li>
      {% endfor %}
      </ul>
      <h3>
        <a href="{% url 'learning_logs:new_topic' %}"><button type="button" class="btn btn-primary btn-sm">Add a new topic</button></a>
      </h3>
    {% endblock content %}
  </body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Login</title>
  </head>
  <body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap4 %}

    {% block header %}
      <h2>Log in to your account.</h2>
    {% endblock header %}

    {% block content %}

      <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
      </form>
    {% endblock content %}
  </body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Register</title>
  </head>
  <body>
    {% extends 'learning_logs/base.html' %}
    {% load bootstrap4 %}
    {% block header %}
      <h2>Register your Account:</h2>
    {% endblock header %}
    {% block content %}
      <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
      </form>
    {% endblock content %}
  </body>
</html>